//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_22._102_Petsevich_Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignments
    {
        public int AssignmentID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
