//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_22._102_Petsevich_Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public int SupplierID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
